INSERT INTO kitchen (kitchen_type) values
(''),
('Nederlands'),
('Frans'),
('Engels'),
('Chinees'),
('Japans'),
('Italiaans'),
('Duits'),
('Indonesisch'),
('Chinees-Indisch'),
('Indiers'),
('Ander Aziatisch'),
('Turks-Arabisch'),
('Scandinavisch'),
('Oost Europees'),
('Americaans'),
('Zuid Americaans'),
('Algemeen'),
('Overige'),
('Add new')