INSERT INTO basis_ingredienten (naam, foto_naam, beschriving) VALUES 
('Kip filet','kipfilet.jpg','Kipfilet is het borstdeel van de kip. Kenmerk van kipfilet is dat deze vetarm en lichtverteerbaar is. Het is daarom een populair alternatief voor varkens- en rundvlees als bestanddeel van de avondmaaltijd. Kipfilet wordt ook veel gebruikt als blokjes of reepjes in roerbakgerechten.'),
('Kippendij','kippendij.jpg','Kipdpendijen is vlees dat afkomstig is van het bovenste gedeelte van de kippenpoot. Dit vlees is donkerder van kleur in vergelijking met de kipfilet, en minstens even smakelijk. Liefhebbers zeggen nog wel eens dat zij dijfilet lekkerder vinden dan de kip...'),
('Kippenpoot','kippenpoot.jpg','Een kippenbout is de grote versie van de kippenpoot met vel, spiermassa en rugstuk. Iets minder handzaam, maar even mals en sappig. Kippenpoot en kippenbout passen in veel verschillende soorten keukens: Italiaans, Frans of Aziatisch.'),
('Kip gehakt','kipgehakt.jpg',''),
('Kip karbonade','kipkarbonade.jpg','Een kipkarbonade komt uit het bovenste deel van de kippenpoot. Het vlees wordt meestal met bot verkocht. Kipkarbonade is erg lekker om te bakken met een marinade of als stoof. Hieronder staat de stoofbereiding voor kipkarbonades.'),
('zout','',''),
('peper','',''),','
('zwarte peper','',''),
('witte peper','',''),
('suiker','',''),
('water','',''),
('runderbouillon','',''),
('kippenbouillon','',''),
('verse tijm','',''),
('tijm','',''),
('verse peterselie','',''),
('peterselie','',''),
('verse korinader','',''),
('koriander','',''),
('rode chilipeper','rodepeper.jpg',''),
('groene chilipeper','groenepeper.jpg',''),
('chilipoeder','',''),
('rode ui','rodeui.jpg','De smaak van de rode ui is scherper dan die van de gewone, gele ui. Uien kunnen rauw, gekookt of gebakken gegeten worden.'), 
('ui','uien.jpg',''),
('knoflook','knoflook.jpg',''),
('knoflookpoeder','',''),
('Olijfolie','',''),
('Zonnebloemolie','',''),
('Sesamolie','',''),
('Rijstolie','',''),
('Licht soyasaus','',''),
('Donker soyasaus','',''),
('Oestersaus','',''),
('Zoete chilisaus','',''),
('Rijstwijn','',''),
('Azijn','',''),
('Mirin','mirin.jpg','Zoete Japanse keukenwijn.'),
('Applelazijn','appelazijn.jpg',''),
('Hoisin saus','hoisinsaus.jpg',''),
('Gember','gember.jpg',''),
('Oregano','',''),
('Djahe','',''),
('Katoembar','',''),
('Ve-tsin','',''),
('Laos','',''),
('Kaneel','',''),
('5 Spices','badminton.jpg','Chinees specerijen melange'),
('Paprikapoeder','',''),
('Rode paprika','',''),
('Gele paprika','',''),
('Groene paprika','',''),
('Kerrie','',''),
('Sesamzaad','',''),
('Kruidnagel','',''),
('Zeezout','',''),
('Majoraan','',''),
('Rozemarijn','',''),
('Nootmuskaat','',''),
('Selieblad','',''),
('Kurkuma','',''),
('Komijnzaad','',''),
('Uienpoeder','',''),
('Anijszaad','',''),
('Worcestershire saus','',''),
('Lente ui','',''),
('Prei','',''),
('Ham','',''),
('Boter','',''),
('Ei','',''),
('Aardappel','',''),
('Vast kokende aardappel','',''),
('Kruimelige aardappel','',''),
('Krieltjes','',''),
('Wortel','',''),
('Bloemkool','',''),
('Spinazie','',''),
('Komkommer','',''),
('Sperziebonen','sperziebonen',''),
('Spruitjes','',''),
('Broccoli','',''),
('Sla','',''),
('Tomaat','',''),
('Tomatenpuree','rettich.jpg',''),
('Aubegine','',''),
('Bosui','',''),
('Snijbonen','',''),
('Cougette','',''),
('Koolraap','',''),
('Rode biet','',''),
('Chinese kool','',''),
('Rettich','rettich.jpg',''),
('Radijs','',''),
('Andijvie','',''),
('Asperges','',''),
('Appel','',''),
('Sinasappel','',''),
('Aardbei','',''),
('Peer','',''),
('Framboos','',''),
('Druiven','',''),
('Krenten','',''),
('Rozijnen','',''),
('Blanke rozijnen','',''),
('Bruine suiker','',''),
('Blauwe bessen','',''),
('Bastaard suiker','',''),
('Kristal suiker','',''),
('Poeder suiker','',''),
('Lichte bastaard suiker','',''),
('Bloem','',''),
('Zelfrijzend bakmeel','',''),
('Bakpoeder','',''),
('Vanille suiker','',''),
('Vanille extract','',''),
('Citroensap','',''),
('Limoensap','',''),
('Appelsap','',''),
('Sinasappelsap','',''),
('Mandarijn','',''),
('Banaan','',''),
('Kiwi','',''),
('Sasperilla','',''),
('Ananas','',''),
('Ananassap','',''),
('Kokosmelk','',''),
('Rendang blokje','',''),
('Biefstuk','',''),
('Gehakt','',''),
('Ossenhaas','',''),
('Entrecote','',''),
('Lende biefstuk','',''),
('Succade lapjes','',''),
('Rundvless','',''),
('Sudderlapjes','',''),
('Varkensfilet','',''),
('Varkensgehakt','',''),
('Karbonade','',''),
('Speklapjes','',''),
('Bacon/Ontbijspek','',''),
('Varkenshaas','',''),
('Zalm','',''),
('Koolvisfilet','',''),
('Makreel','',''),
('Lekkerbekje','',''),
('Kaas','',''),
('Pasta','',''),
('Spagetti','',''),
('Macaroni','',''),
('Erwten','',''),
('Rijst','',''),
('Rijstazijn','',''),
('Kleefrijst','',''),
('Noriblad','',''),
('Tonijn','',''),
('Avacado','',''),
('Surimi','',''),
('Puur chocolade','',''),
('Melk chocolade','',''),
('Witte chocolade','',''),
('Marsepein','',''),
('Melk','',''),
('Joghurt','',''),
('Soep kip','',''),
('Mozzarella','',''),
('Champignon','',''),
('Bleekselderij','',''),
('Slagroom','',''),
('Rode bessen','',''),
('Brood','',''),
('Bruin brood','',''),
('Volkoren brood','',''),
('groentebouillon','kipgehakt.jpg','Makkelijk om een greontebouillonblokje met (warm) water te mengen. Geeft een volle smaak aan sopen en sausen waar geen vlees in wordt gekookt.'),
('Roomboter','kipfilet.jpg',''),
('Laurierbladeren','',''),
('Tomaten','',''),
('Soepgroenten','',''),
('vermicelli','',''),
('Mosterd','',''),
('Mayonaise','',''),
('Griekse yoghurt','',''),
('Franse mosterd','',''),
('Honing','',''),
('Amsterdamse uien','',''),
('Witte kool','',''),
('Cooking oil','',''),
('eiwit','',''),
('maizena','',''),