DROP TABLE recept;
CREATE TABLE recept (
  id int NOT NULL GENERATED ALWAYS AS IDENTITY,
  naam varchar(60) NOT NULL,
  beschrijving varchar(500) DEFAULT NULL,
  notes varchar(200) DEFAULT NULL,
  aantal_person()en int DEFAULT NULL,
  suiker int DEFAULT NULL,
  energie int DEFAULT NULL,
  eiwit int DEFAULT NULL,
  koolhydraten int DEFAULT NULL,
  vet int DEFAULT NULL,
  natrium int DEFAULT NULL,
  vezels int DEFAULT NULL,
  keuken varchar(45) DEFAULT NULL,
  maal_type varchar(45) DEFAULT NULL,
  thema varchar(45) DEFAULT NULL,
  tags int DEFAULT NULL,
  stappen varchar(2100) DEFAULT NULL,
  onderdelen int DEFAULT NULL,
  extras varchar(250) DEFAULT NULL,
  internet_link varchar(100) DEFAULT NULL,
  foto_naam varchar(100) DEFAULT NULL,
  prep_tijd int DEFAULT NULL,
  kook_tijd int DEFAULT NULL,
  ingredienten varchar(2100) DEFAULT NULL,
  tag1 varchar(20) DEFAULT NULL,
  tag2 varchar(20) DEFAULT NULL,
  tag3 varchar(20) DEFAULT NULL,
  tag4 varchar(20) DEFAULT NULL,
  tag5 varchar(20) DEFAULT NULL,
  tag6 varchar(20) DEFAULT NULL,
  tag7 varchar(20) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id_UNIQUE (id),
  UNIQUE KEY naam_UNIQUE (naam)
) 